language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-reverseproxy .
  - docker tag udagram-api-reverseproxy vupa1/udagram-api-reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push vupa1/udagram-api-reverseproxy

#deploy:
#  provider: script
#  script: bash docker_push
#  on:
#    branch: master
