language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version
  
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy vupa1/reverseproxy:v2

  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend vupa1/udagram-frontend:v2

  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user vupa1/udagram-api-user:v2

  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed vupa1/udagram-api-feed:v2

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push vupa1/reverseproxy:v2
  - docker push vupa1/udagram-frontend:v2
  - docker push vupa1/udagram-api-user:v2
  - docker push vupa1/udagram-api-feed:v2

#deploy:
#  provider: script
#  script: bash docker_push
#  on:
#    branch: master
