apiVersion: apps/v2
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
        app: reverseproxy
    spec:
      containers:
      - image: vupa1/reverseproxy:v2
        name: reverseproxy
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"     
        ports:
        - containerPort: 8080
      restartPolicy: Always